[book]
authors = ["Hatix Ntsoa"]
language = "en"
multilingual = false
src = "src"
title = "Web Application Basics"
CTTO = "TryHackMe - https://tryhackme.com/r/room/webapplicationbasics"

[output.html]
# Set the base URL for GitHub Pages to resolve relative paths properly
site-url = "https://hatixntsoa.github.io/web.application.basics"